<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>ZNext</RootNamespace>
    <AssemblyTitle>ZNext Launcher</AssemblyTitle>
    <Product>ZNext Launcher</Product>
    <FileDescription>ZNext Launcher</FileDescription>
    <PackageLicenseExpression>GPL-3.0-only</PackageLicenseExpression>
    <ApplicationIcon>Assets\ZNext.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AppxManifest>Package.appxmanifest</AppxManifest>
    <Platforms>x86;x64;ARM64;AnyCPU</Platforms>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <PublishProfile>win-$(Platform).pubxml</PublishProfile>
    <UseWinUI>true</UseWinUI>
    <EnableMsixTooling>true</EnableMsixTooling>
    <AppxPackage>true</AppxPackage>
    <WindowsPackageType>MSIX</WindowsPackageType>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>

    <InvariantGlobalization>false</InvariantGlobalization>
    <EventSourceSupport>false</EventSourceSupport>
    <ZNextLanguageResourceDirectory>Languages</ZNextLanguageResourceDirectory>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DisableXamlDiagnostics>true</DisableXamlDiagnostics>
    <GenerateLibraryLayout>false</GenerateLibraryLayout>
    <EnableUnmanagedNativeCode>false</EnableUnmanagedNativeCode>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Assets\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>

  <ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <ProjectCapability Include="Msix" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.250907003" />
    <PackageReference Include="Microsoft.Windows.CsWinRT" Version="2.2.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.4948" />
    <PackageReference Include="CommunityToolkit.WinUI.Controls.SettingsControls" Version="8.2.250402" />
  </ItemGroup>

  <PropertyGroup>
    <PublishReadyToRun Condition="'$(Configuration)' == 'Debug'">False</PublishReadyToRun>
    <PublishReadyToRun Condition="'$(Configuration)' != 'Debug'">True</PublishReadyToRun>
    <PublishTrimmed Condition="'$(Configuration)' == 'Debug'">False</PublishTrimmed>
    <PublishTrimmed Condition="'$(Configuration)' != 'Debug'">True</PublishTrimmed>
    <AppxPackageSigningEnabled>True</AppxPackageSigningEnabled>
    <PackageCertificateThumbprint>ED00BA66326C8F7AC851B6003B8CDCC51BDFA002</PackageCertificateThumbprint>
    <DefaultLanguage>zh-cn</DefaultLanguage>
  </PropertyGroup>

  <PropertyGroup Condition="'$(DisableHasPackageAndPublishMenuAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <HasPackageAndPublishMenu>true</HasPackageAndPublishMenu>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <DefineConstants>$(DefineConstants);DISABLE_XAML_GENERATED_BREAK_ON_UNHANDLED_EXCEPTION</DefineConstants>
  </PropertyGroup>

  <Target Name="MoveUnpackagedLanguageResources" AfterTargets="Publish" Condition="'$(GenerateAppxPackageOnBuild)' != 'true' and '$(PublishDir)' != ''">
    <Exec Command="powershell -NoProfile -ExecutionPolicy Bypass -File &quot;$(MSBuildProjectDirectory)\scripts\Move-UnpackagedLanguageResources.ps1&quot; -PublishDir &quot;$(PublishDir).&quot; -LanguageRoot &quot;$(ZNextLanguageResourceDirectory)&quot;" />
  </Target>

</Project>
